---
# Start MapReduce.
- name: Start Resource Manager
  action: service name=hadoop-yarn-resourcemanager state=started
  only_if: '$is_resource_manager'

- name: Start Node Manager on datanodes
  action: service name=hadoop-yarn-nodemanager state=started
  only_if: '$is_worker'

- name: Start History Server
  action: service name=hadoop-mapreduce-historyserver state=started
  only_if: '$is_history_server'
